PartooHub/developers-website

- rest_api/v2/paths/index.yml
- rest_api/v2/paths/reviews_analytics/get_qualitative_evolution.yml
- rest_api/v2/paths/reviews_analytics/get_quantitative_evolution.yml
- rest_api/v2/tags/index.yml
Description
As a Product Validator, when I come to the Partoo documentation, I see a specific section for Review Analytics. 
I do not see anymore the part of Review Analytics in the Review Management section
Jira : [RT-1268]
[RT-1268]: https://partoo.atlassian.net/browse/RT-1268
> [RT-1268] Add section Reviews Analytics

- rest_api/v2/components/index.yml
https://partoo.atlassian.net/secure/RapidBoard.jspa?rapidView=8&projectKey=MT&modal=detail&selectedIssue=MT-1151
> [MT-1151] - Add Multiple Select Image example to api doc

- rest_api/v2/components/index.yml
- rest_api/v2/paths/category/get_categories.yml
- rest_api/v2/paths/index.yml
[Story](https://partoo.atlassian.net/secure/RapidBoard.jspa?rapidView=27&projectKey=JT&modal=detail&selectedIssue=JT-47)
* endpoint : https://preprod.partoo.co/api/v2/categories
> [JT-47] /api/v2/categories documentation

- rest_api/v2/components/index.yml
- rest_api/v2/paths/business/post_create.yml
Add more explicit information on each field of the business to avoid having clients keep asking us about stuff
> Add proper description to business fields

- rest_api/v2/components/index.yml
- rest_api/v2/paths/category/get_categories.yml
- rest_api/v2/paths/index.yml
> [JT-99][JT-107] new query filters in GET /api/v2/categories

- rest_api/v2/components/index.yml
- rest_api/v2/paths/index.yml
- rest_api/v2/paths/reply_templates/delete.yml
- rest_api/v2/paths/reply_templates/placeholders.yml
- rest_api/v2/paths/reply_templates/post.yml
- rest_api/v2/paths/reply_templates/search.yml
- rest_api/v2/tags/index.yml
Adding Documentation for Reply templates.
> Adding Search Post and Delete template methods

- rest_api/v2/components/index.yml
- rest_api/v2/paths/category/get_by_id.yml
- rest_api/v2/paths/category/get_search.yml
- rest_api/v2/paths/index.yml
/!\ DO NOT MERGE /!\
NEW CATEGORIES DOC
> [JT-132] Update Api Doc for CategorySql

- rest_api/v2/paths/index.yml
- rest_api/v2/paths/reviews/delete_reply.yml
- rest_api/v2/paths/reviews/modify_reply.yml
- rest_api/v2/paths/reviews/post_reply.yml
Change route for posting a reply to a review, modifying a reply of a review and deleting a reply of a review
> Rework review api routes

- rest_api/v2/components/index.yml
- rest_api/v2/paths/api_keys/get_api_keys.yml
- rest_api/v2/paths/index.yml
Put in place basic components for api keys documentation.
> Add get api keys list documentation

- rest_api/v2/paths/api_keys/revoke_api_key.yml
- rest_api/v2/paths/index.yml
> Update doc with post revoke route

- rest_api/v2/components/index.yml
- rest_api/v2/paths/api_keys/update_api_keys.yml
- rest_api/v2/paths/index.yml
> [JT-193] - Update api_keys route

- rest_api/v2/components/index.yml
> [JT-227] - Add inactive filter and user data for api keys list

- rest_api/v2/components/index.yml
> [JT-253] add revocked_by_name

- rest_api/v2/components/index.yml
- rest_api/v2/paths/index.yml
> [JT-247] - Patch update changed to put update and null expiration_date possible

- rest_api/v2/components/index.yml
> [JT-275] - New serializer changes

- rest_api/v2/components/index.yml
- rest_api/v2/paths/attributes/get.yml
- rest_api/v2/paths/business/get_attributes.yml
- rest_api/v2/paths/business/post_attributes.yml
- rest_api/v2/paths/index.yml
- rest_api/v2/tags/index.yml
WHY
See email sent in comments - by provider Editus
WHAT
AS an API User, WHEN I go to the API doc, I see GET request on attribute endpoint is documented so that I can use it in my own app
> [MT-1443] - Document_Attributes_endpoints for Org Admin

- rest_api/v2/components/index.yml
- rest_api/v2/paths/api_keys/update_api_keys.yml
Link to JIRA: [JT-323]
Add ip_whitelist to documentation of GET/PUT ApiKey endpoints
[JT-323]: https://partoo.atlassian.net/browse/JT-323
> [JT-323] - Add API Key's IP whitelist to get/update documentation

- rest_api/v2/components/index.yml
- rest_api/v2/paths/business/post_create.yml
- rest_api/v2/paths/business/post_update.yml
Update Preprod & Prod API Doc that the following endpoint field/param will be deprecated the 15 July 2021
Create Business
- Mandatory phone field
Search for business
- subscribed_to_pm will be removed from params
- subscribed_to_rm will be removed from params
- videos will be removed from response
- siret will be removed from response
- news will be removed from response
Get Business
- videos will be removed from response
- siret will be removed from response
- news will be removed from response
Update Business
- videos will be removed from response
- news will be removed from response
> [BPT] add warning in phone field

- Makefile
- README.md
- rest_api/v2/tags/index.yml
Add a section for technical support in the REST documentation
> Add support section for Rest api

- rest_api/v2/components/index.yml
- rest_api/v2/paths/authorize/get.yml
- rest_api/v2/paths/authorize/post.yml
- rest_api/v2/paths/authorize/post_revoke.yml
- rest_api/v2/paths/business/post_create.yml
- rest_api/v2/paths/category/get_search.yml
Consistent warning message on API breaking changes
> Consistent warning message on API breaking changes

- rest_api/v2/tags/changeLogs.yml
- rest_api/v2/tags/index.yml
> [JT-277] - Add change log section on doc

- rest_api/v2/tags/changeLogs.yml
> [JT-277] - Change logs changed

- rest_api/v2/components/index.yml
> Clearer text on country code usage

- rest_api/v2/components/index.yml
- rest_api/v2/paths/business/post_update.yml
- rest_api/v2/paths/category/get_search.yml
- rest_api/v2/tags/index.yml
Check [here](https://partoo.atlassian.net/secure/RapidBoard.jspa?rapidView=27&projectKey=JT&modal=detail&selectedIssue=JT-453) for further information:
> [JT-453] - Rework categories to ease understanding

- rest_api/v2/components/index.yml
Modifications to getMyUser after we added shadow_user_id and created_at to user following modifications on script loading in the app
> Adding information for getMyUser

- js_sdk/guides/callbacks.rst
[BPT-1606]
[BPT-1606]: https://partoo.atlassian.net/browse/BPT-1606
> [BPT-1606] add pm_view_go_to_partner_connection_click doc

- README.md
- package.json
- rest_api/v2/paths/review_booster/send_invitation/post.yml
[MT-1675]
[MT-1675]: https://partoo.atlassian.net/browse/MT-1675
> [MT-1675] Update RB, update local port
